Ensure tag is deployed with right digest via pipeline

diff --git a/helm/templates/tekton/pipeline.yaml b/helm/templates/tekton/pipeline.yaml
--- a/helm/templates/tekton/pipeline.yaml
+++ b/helm/templates/tekton/pipeline.yaml
@@ -112,7 +112,24 @@ spec:
 
             oc tag $(params.IMAGE_NAME)@$(tasks.buildah.results.IMAGE_DIGEST) quinoa-wind-turbine:$(params.IMAGE_TAG)
             
-            oc rollout latest dc/quinoa-wind-turbine || true 
+            oc rollout latest dc/quinoa-wind-turbine || true
+
+            echo "--- New stuff: Checking if really the new build image digest is deployed ---"
+
+            export CURRENT_IMAGE=$(oc get dc quinoa-wind-turbine -o jsonpath='{.spec.template.spec.containers[0].image}{"\n"}')
+            export CURRENT_DIGEST=$(echo $CURRENT_IMAGE | cut -d "@" -f2-)
+            echo "current digest = $CURRENT_DIGEST"
+            
+            diff <(echo "$$RESULT_DIGEST") <(echo "$CURRENT_DIGEST")
+            # [ "$RESULT_DIGEST" = "$CURRENT_DIGEST" ]; echo "$?" 
+
+            if [ "$RESULT_DIGEST" = "$CURRENT_DIGEST" ]
+            then
+                echo "Current digest is deployed!"
+            else
+                echo "ERROR!"
+            fi
+
         - name: VERSION
           value: latest
       taskRef:
